apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-type-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-type-service
  template:
    metadata:
      labels:
        app: expense-type-service
    spec:
      containers:
        - name: expense-type-service
          image: 920871346103.dkr.ecr.eu-north-1.amazonaws.com/expense-type-service
          ports:
            - containerPort: 8080