apiVersion: v1
kind: Service
metadata:
  name: expense-type-service
spec:
  type: LoadBalancer
  selector:
    app: expense-type-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080